### ISSUE TITLE
How to use this package from another package?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/utils#1]
I tried to see what the command `EpimorphismByGenerators` does, but failed, because it does not define this function:
```
gap> LoadPackage("utils", false);
true
gap> EpimorphismByGenerators;
Error, Variable: 'EpimorphismByGenerators' must have a value
not in any function at line 2 of *stdin*
```

Apparently, it doesn't define it because it detects that I have RCWA installed. But I do not have RCWA loaded!

So, it seems if I wanted to use that function in a package, I would have to depend on both RCWA and utils in my package. That is quite inconvenient. Is that the intended behavior?

**Comment by cdwensley** [comment]
In a sense that is the intended behaviour while the function is in transition and, if you wanted to use the function, you would be better off loading RCWA at this stage.  I now intend to add a warning in the manual for each such function.  (This problem did not arise when using the previous transitional procedure, but that involved alterations to global.g and oper.g which were unpopular.) 
I am very grateful that you have taken the time to provide some feedback in this and the two following issues.  Your long list of comments on Dec.17 were equally useful, and were passed on to the package authors, but they have not had time to respond.
