### ISSUE TITLE
Utils tests fail in stable-4.9 when all packages are loaded

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/utils#12]
For example in https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/jobs/398642379
```
########> Diff in /home/gap/inst/gap-stable-4.9/pkg/utils-0.54/tst/print.tst:
53
# Input is:
PrintSelection( f2, 20, 20, 100 ); 
# Expected output:
20 : f2*f1^2
40 : f2*f1*f2
60 : f1*f2*f1^2
80 : (f2*f1)^2
100 : f1*f2^2*f1^-1
# But found:
20 : f1^-2*f2
40 : f2^-1*f1*f2^-1
60 : f1^-2*f2*f1^-1
80 : f1^-1*f2^3
100 : f1*f2*f1^-1*f2^-1
########
########> Diff in /home/gap/inst/gap-stable-4.9/pkg/utils-0.54/tst/print.tst:
59
# Input is:
PrintSelection( f2, [11..15] );
# Expected output:
11 : f2^-1*f1^-1
12 : f1*f2
13 : f1^-1*f2
14 : f1*f2^-1
15 : f1^-1*f2^-1
# But found:
11 : f1*f2
12 : f2^-1*f1^-1
13 : f2^-1*f1
14 : f2^-2
15 : f2*f1^-1
########
```
This happened after recent check for package updates. Perhaps this test can be improved to be more robust.

**Comment by cdwensley** [comment]
There is no need for fp-groups to be used in a test for PrintSelection. 
The file utils/tst/print.tst has been revised and Utils version 0.56 released.

**Comment by cdwensley** [comment]
Too hasty: the revised print.tst now fails.

**Comment by cdwensley** [comment]
It seems there has always been a problem in trying to run a single test rather than all the tests via tst/testall.g.  All tests now Read("tst/loadall.g"); which solves that problem.  Version 0.57 released.
