### ISSUE TITLE
EpimorphismByGenerators and EpimorphismByGeneratorsNC

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/utils#2]
So `EpimorphismByGenerators` is an alias for `EpimorphismByGeneratorsNC`, and both do no checking. This is contrary to the usual conventions (and potentially quite dangerous for inexperienced users).

Moreover, both do _exactly_ the same thing as `GroupHomomorphismByImagesNC` (which can also be called with just two parameters).

So, all in all, I wonder about the purpose of this tool? Is it wise to have a potentially dangerous operation without an NC suffix, which does something another well-documented function already does? OK, it saves a few letters...

**Comment by cdwensley** [comment]
This comment is really about "what functions are suitable to be included in Utils?", and "what are the appropriate actions which the Utils maintainer might make?".  So far I have, in the main, just copied the code from another package. If the function is documented there, then copying it to Utils is not so very different.  Undocumented functions are another matter, and probably should have more tests added, where appropriate.

**Comment by cdwensley** [comment]
A guiding principle of the Utils package is that transferred functions will not be altered without the agreement of the original author.  In this case a simple fix would be to only use EpimorphismByGeneratorsNC in RCWA and then add tests to EpimorphismByGenerators.  Since the author is not agreeable to this, no changes will be made, but adequate warnings will be included in the manual.

**Comment by fingolfin** [comment]
I just noticed that this issue was closed, and am re-opening it for reconsideration: In particular, I don't think the warning in the utils manual is explicit enough about the fact that the pair `EpimorphismByGenerators` and `EpimorphismByGeneratorsNC` is in direct violation to conventions used by all of the rest of GAP. I really wonder what the original author's (presuamble Stefan Kohl?) defense of this gross violation is.

As I understood it, the idea behind utils is to move stuff there which is potentially useful for more than one package. But that should mean things added there are well-tested, documented, and match the general design principles behind GAP. This function violates at least the last point.

Also, as I suggested earlier, `EpimorphismByGeneratorsNC` is basically an alias for (a special case of) GroupHomomorphismByImagesNC. So its implementation could be replaced by this shorter one:
```
InstallMethod( EpimorphismByGeneratorsNC, "for groups", [ IsGroup, IsGroup ],
  GroupHomomorphismByImagesNC);
```

**Comment by cdwensley** [comment]
I rather tend to agree.  The function EpimorphismByGenerators occurs just 4 times in rcwa: 3 times in the manual and once in a test.  It would be a simple matter to replace this with GroupHomomorphismByImagesNC.  Then  EpimorphismByGenerators(NC) could be removed from Utils.  But this requires Stefan to agree.

**Comment by alex-konovalov** [comment]
Ping to @Stefan-Kohl - just in case, as I can't see if you're receiving notifications from this repository.

**Comment by Stefan-Kohl** [comment]
I heavily use EpimorphismByGenerators interactively, and would find it rather inconvenient to switch to something more clumsy like GroupHomomorphismByImagesNC. That there is not always an epimorphism as specified is obvious, and it is also obvious that checks are not feasible (the problem being algorithmically undecidable). For that reason it is clear that there are no checks, and the name is hence not misleading - just to the contrary, having an NC version and a non-NC version would falsely suggest that a proper argument check is algorithmically possible.

**Comment by cdwensley** [comment]
That being the case, how about removing the NC version and changing to something like the following? 
Currently, it is documenting the existence of NC and non-NC versions which might cause some confusion. 

InstallGlobalFunction( EpimorphismByGenerators,
function ( D1, D2 )
    if ( IsGroup(D1) and IsGroup(D2) ) then 
        return GroupHomomorphismByImagesNC( D1, D2, 
                   GeneratorsOfGroup(D1), GeneratorsOfGroup(D2) );
    else
        some suitable error message 
    fi; 
end );

**Comment by Stefan-Kohl** [comment]
Thinking a bit more about the issue, in all cases where I used this function so far the first argument was a free group. So making EpimorphismByGenerators work only in this case would be an option. -- Then argument checks are of course trivial.

**Comment by fingolfin** [comment]
Just removing the *NC variant would already be a nice improvement in my view. Thanks
