### ISSUE TITLE
Get rid of the dummy argument in `PrintApplicableMethod`

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/utils#24]
If called with more than two arguments, `PrintApplicableMethod` needs to be called with the third argument being zero. See
```
gap> PrintApplicableMethod( IsCyclic, [Group(())], 1, 2 );
Error, Usage: PrintApplicableMethod( fn, params [, 0, n ] ); at /home/sergio/projects/gap/pkg/utils-0.58/lib/others.gi:33 called from
...
```
Instead one could rather leave out the third argument.

**Comment by cdwensley** [comment]
PrintApplicableMethod has been removed - see Utils Issue #22.
