### ISSUE TITLE
Utils tests fail in GAP stable-4.10 branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/utils#31]
See e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/546120395 when no packages are loaded

**Comment by cdwensley** [comment]
Hopefully fixed this problem by adding "imi:=[]; im2:=[];" in utils-0.65 released today. 
But this "unbound global variable" error seems to be a gapdev problem, so I have raised a gapdev issue at  https://github.com/gap-system/gap/issues/3555.

**Comment by alex-konovalov** [comment]
Thanks @cdwensley - fixed indeed, see e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-staging/jobs/562123500
