### ISSUE TITLE
SendEmail documentation is incomplete

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/utils#4]
The `SendEmail` documentation says: "... works only under UNIX."

Assuming that by "UNIX" you mean a "UNIX compatible" system such as Linux or Mac OS X, one may want to augment this documentation, because it is misleading: E.g. on most desktop machines, this will *not* work, because those machines have not been configured to transfer mails; and then in the next step, many networks (in particular in universities) will prevent your emails from getting through, because, well, many of them have been hurt badly by spambots taking over badly secured machines in their networks.

E.g. on none of the computers I have access to can I actually use this command to send emails. Is it actually different for you?

**Comment by cdwensley** [comment]
Documentation error: the three functions DownloadFile, SendEmail and EmailLogFile were not included in the 0.25 distribution, but remained in the manual.

**Comment by fingolfin** [comment]
Thanks! Though I don't see how 1247d56ba75adedb198d7accfd84410287b9b29c is fixing this issue... but I see that it was fixed a bit before in 85ba0580f3f63e59be11821753bb18c49b6ae947 :-)
