### ISSUE TITLE
Utils website

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/utils#5]
Utils' `PackageInfo.g` files states that the website is http://pages.bangor.ac.uk/~mas023/chda/utils/ but that seems not to provide any details except that being the path to downloads.

**Comment by cdwensley** [comment]
All the Bangor packages are organised this way, with links to downloads and to a file which introduces the various packages.  I could change this next time I'm in Bangor.

**Comment by alex-konovalov** [comment]
Ah, I haven't realised that there is http://pages.bangor.ac.uk/~mas023/chda/intro.html with an overview of all your packages! But still, that page does not contain links to downloads, package manuals etc.

I suggest to think carefully and not to rush with changing that page(s) - since your packages are now hosted on Github, you may think of using @fingolfin's PackageMaker and host the packages' websites on GitHub too, or using it to host at Bangor their websites generated with PackageMaker - both use cases are possible.

**Comment by fingolfin** [comment]
My PackageMaker has nothing to do with websites as such -- it just is one way to make use of my tools for that, i.e. https://github.com/fingolfin/GitHubPagesForGAP  and also https://github.com/fingolfin/ReleaseTools

**Comment by cdwensley** [comment]
Moving the Utils PackageWWWHome to GitHub was always the plan in the long term, but it seems that GitHubPagesForGAP makes it very straightforward.  Version 0.26 is now at http://gap-packages.github.io/utils/.  The only snag I've found so far is that the .zip download does not appear in the black, top-left box, though it is listed in _data/package.yml.  Stefan prefers to use the .zip archive.  What file do I need to edit?

**Comment by cdwensley** [comment]
Correction: the .zip file is there now.  Wonderful!
