### ISSUE TITLE
Is Flatten(list, level) a good fit for utils or better for core GAP?

### ISSUE THREAD

**Issue by kiryph** [gap-packages/utils#63]
GAP provides the method [`Flat(list)`](https://docs.gap-system.org/doc/ref/chap21_mj.html#X7FA272D984EF82ED) to flatten a nested list completely. However, I miss a method which will leave the inner level intact (e.g. a nested list of row vectors should become a list of row vectors). I have not found any in core gap or any of the packages given in https://github.com/gap-packages/

[Sage](https://doc.sagemath.org/html/en/reference/misc/sage/misc/flatten.html) and [Mathematica](https://reference.wolfram.com/language/ref/Flatten.html) (and probably more) provide an argument for their "flatten" methods to specify how many levels of a nested list should be flatten. This would be good enough for me e.g. I do not need a negative level specification counting from inwards.

Could a similar method be added to gap or gap package utils?

I have written my own method and added to my gaprc:

```gap
FlattenOuterLevel := function( list )
  local new;
  new := [];
  Perform(list, function(elm) if IsList(elm) then Append(new, elm); else Add(new,elm); fi; end);
  return new;
end;

Flatten := function( list , level )
  local new, i;
  if not IsPosInt(level) then
     Error("level for Flatten( list, level) must be a positive integer. Given \"", level, "\"");
  fi;
  new := StructuralCopy(list);
  for i in [1..level] do
    new := FlattenOuterLevel(new);
    if i <> level and not ForAny(new, IsList) then
      Info(InfoWarning, 1, "Flatten(list, level=", level, " ) stopped at level ", i, ". No nested lists anymore.");
      return new;
    fi;
  od;
  return new;
end;
```

This is only a quick implementation without any tests (e.g. regarding deep copy).
Also the naming is up for debate, e.g. `Flat()` could be extended to have a second form. I actually prefer shorter names and arguments should not be repeated in function names: `FlattenOuterLevel` should not be exposed and `Flatten(list, 1)` or `Flat(list, 1)` should be the way to use it.

**Comment by cdwensley** [comment]
Very happy to add this to Utils unless someone thinks this is not the best place.

**Comment by ChrisJefferson** [comment]
I personally would be happy for this function to be inside GAP, and the current `Flat` function only takes one parameter, so it's easy to be backwards compatible. I have wanted this myself in the past, usually just removing one level. You can do one level with `Concatenation`, but that's not super-obvious.

**Comment by kiryph** [comment]
> You can do one level with Concatenation, but that's not super-obvious.

Thank you for pointing this out.

An example for illustration:
```gap
gap> Concatenation([ [ [1, 0] , [2, 0], [3, 0] ], [ [2, 0], [3, 0], [4, 0] ], [ [3, 0], [4, 0], [5, 0] ] ]);
[ [ 1, 0 ], [ 2, 0 ], [ 3, 0 ], [ 2, 0 ], [ 3, 0 ], [ 4, 0 ], [ 3, 0 ], [ 4, 0 ], [ 5, 0 ] ]
```

However, `Concatenation` fails, if some elements of the outer list are not lists:

```gap
gap> nested := [ 1, [ [2, 22], 3 ], [ [ 1, 2 ], 3 ] ];
gap> Concatenation(nested);
Error, FuncAPPEND_LIST_INTR: <list1> must be a mutable list (not the integer 1) in
  Append( res, arg[i] ); at /usr/local/Cellar/gap/4.12.1/libexec/lib/list.gi:2086 called from
<function "Concatenation">( <arguments> )
 called from read-eval loop at *stdin*:6
type 'quit;' to quit to outer loop
```

A general Flatten method can handle this as well:
```gap
gap> Flatten(nested, 1);
[ 1, [ 2, 22 ], 3, [ 1, 2 ], 3 ]
```

But for my particular situation `Concatenation` is fine and is a core GAP function which solves the task I was looking for.

**Comment by cdwensley** [comment]
It seems this is no longer an issue for Utils.
