### ISSUE TITLE
Add the function `DirectSumDecompositionMatrix`.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/utils#64]
Recently, based on [this question](https://lists.uni-kl.de/gap/arc/forum/2023-06/msg00011.html) filed by me, [Pedro A. García Sánchez](https://github.com/pedritomelenas) ultimately implemented the following function:

```gap
DirectSumDecompositionMatrix:=function(l)
    
  local nr,nc,i,j,nzr,nzb,rest,bls;

  rest:=StructuralCopy(l);
  nr:=Length(rest);
  nc:=Length(rest[1]);
  bls:=[];
  i:=1;
  j:=1;
  while nr>0 or nc>0 do
      nzr:=true;
      nzb:=true;
      while nzr or nzb do
          nzr:=ForAny([1..i],i1->ForAny([j+1..nc],j1->rest[i1][j1]<>0));
          nzb:=ForAny([i+1..nr],i1->ForAny([1..j],j1->rest[i1][j1]<>0));
          if nzr then
              j:=j+1;
          fi;
          if nzb then
              i:=i+1;
          fi;
      od;
      Add(bls,List([1..i],i1->rest[i1]{[1..j]}));
      rest:=List([i+1..nr],i1->rest[i1]{[j+1..nc]});
      nr:=nr-i;
      nc:=nc-j;
      i:=1; j:=1;
  od;
  return bls;

end;
```
The above implementation is rather flexible, e.g., it also works for non-square matrices. See the following testings for more detail:

```gap
gap> M:=DirectSumMat([[[1,2,3],[4,5,6]], [[7]]]);
[ [ 1, 2, 3, 0 ], [ 4, 5, 6, 0 ], [ 0, 0, 0, 7 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 1, 2, 3 ], [ 4, 5, 6 ] ], [ [ 7 ] ] ]
gap> M:=[[0,1,0],[1,0,0],[0,0,1]];
[ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, 1 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 0, 1 ], [ 1, 0 ] ], [ [ 1 ] ] ]
gap> M:=[ [ 1, 2, 0,0 ], [ 3, 4, 0,0 ], [ 0, 0, 6 ,0], [0,0,0,7] ];
[ [ 1, 2, 0, 0 ], [ 3, 4, 0, 0 ], [ 0, 0, 6, 0 ], [ 0, 0, 0, 7 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 1, 2 ], [ 3, 4 ] ], [ [ 6 ] ], [ [ 7 ] ] ]
gap> M:=[ [ 8, -4, 0 ], [ -4, 8, 0 ], [ 0, 0, 6 ] ];
[ [ 8, -4, 0 ], [ -4, 8, 0 ], [ 0, 0, 6 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 8, -4 ], [ -4, 8 ] ], [ [ 6 ] ] ]
gap> M:=[ [ 32, -4, 0 ], [ -4, 8, 0 ], [ 0, 0, 6 ] ];
[ [ 32, -4, 0 ], [ -4, 8, 0 ], [ 0, 0, 6 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 32, -4 ], [ -4, 8 ] ], [ [ 6 ] ] ]
gap> M:=[ [ 1, 2, 0 ], [ 3, 4, 0 ], [ 0, 0, 6 ] ];
[ [ 1, 2, 0 ], [ 3, 4, 0 ], [ 0, 0, 6 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 1, 2 ], [ 3, 4 ] ], [ [ 6 ] ] ]
```
Considering that there is no such function in GAP, I recommend adding it to the utils package.

Regards,
Zhao

**Comment by cdwensley** [comment]
Happy to do this if Pedro is also happy.

**Comment by hongyi-zhao** [comment]
I have confirmed this with Pedro via email:

> Fine. My username on github is @pedritomelenas.
> 
> El 13/6/23 a las 15:33, Hongyi Zhao escribió:
> > On Mon, Jun 12, 2023 at 10:53 PM Pedro A. García Sánchez <pedro@ugr.es> wrote:
> >> Great.
> > I suggested adding your function to the utils package. See here [1]
> > for more details.
> >
> > [1] https://urldefense.com/v3/__https://github.com/gap-packages/utils/issues/64__;!!D9dNQwwGXtA!QJriOnwy5qzghYnCtf8MdumvJQb3oYBjlrK_qvpkWSk4LgVh_6O9UeUS7odKdven9bFsR3VEZRoQbgP7$

![image](https://github.com/gap-packages/utils/assets/11155854/6db85ebf-df12-4dda-bf92-15eed8b4a030)

**Comment by pedritomelenas** [comment]
If you plan to add this, some error checking should be necessary. I simply replied to @hongyi-zhao request on the gap forum, and thought is was ment for personal use. I am happy if the code is included in utils package, as I said the email copied above. If for some reason you think that it does not fit in utils package, then it is also perfect for me if it is included elsewhere or nowhere at all. So, please make use of the code if you find it useful.

I do not know what the elements of the matrix might be, so I propose to change things like `a<>0` to `not(IsZero(a))`. Also, something like checking if the argument is a matrix should be added. I usually check this with `IsRectangularTable` and then check if all its elements are integers (since I usually work with integers), but I guess that in this setting `IsMatrix(l)` would be better.

```
	if not(IsMatrix(l))  then
		Error("The argument must be a matrix.");
	fi;
```

**Comment by pedritomelenas** [comment]
@cdwensley, nice example. The implementation is eager and finds the a block [[0,2]]. I will see if I can fix it.

**Comment by pedritomelenas** [comment]
Is in this case the decomposition [ [[0,2]],[[0,0],[0,0],[3,0]] ] acceptable? If so, we may have not "unique factorizations"

**Comment by cdwensley** [comment]
Depends what you mean by a direct sum decomposition.  Is not the direct sum of your proposal: 
[[0,2,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,3,0]] ?   which is not the same as the original mat4.

**Comment by pedritomelenas** [comment]
Please, send to me the definition of direct sum. I though it was the one given in  https://en.wikipedia.org/wiki/Matrix_addition#:~:text=The%20direct%20sum%20of%20matrices,sum%20of%20their%20adjacency%20matrices.

**Comment by pedritomelenas** [comment]
By the way, if I remember well, @hongyi-zhao told me that there would be no zero rows, and this is why I did not take them into account.

**Comment by cdwensley** [comment]
Yes, this is the correct definition.  In the example the sum of (2 x 3) with (2 x 2 ) is (4 x 5). 
In general, the sum of (m x n), (p x q) and (r x s) is (m+p+r) x (n+q+s). 
So a (1 x 2), (2 x 2) and (1 x 2) combine to give (4 x 6).

**Comment by cdwensley** [comment]
Ah - the misunderstanding is mine.  I thought you were proposing [ [[0,2]], [[0,0],[0,0]], [[3,0]] ]. 
So your decomposition _is_ correct, and there is not a unique answer.   All along I thought that it was a decomposition into square matrices that was required, but I now see that that need not be the case.  Sorry for the noise!

**Comment by pedritomelenas** [comment]
No, thank you for the clarification! Actually, the first thing I tried was running through the diagonal. I will make it eager to swallow as many zero rows as possible, and this would probably fix the issue.

**Comment by pedritomelenas** [comment]
Let me see if you are happy with this approach. Actually one could produce all possible outputs ... 

```
DirectSumDecompositionMatrix:=function(l)
    
    local nr,nc,i,j,nzr,nzb,rest,bls,nbls;

    rest:=StructuralCopy(l);
    nr:=Length(rest);
    nc:=Length(rest[1]);
    bls:=[];
    i:=1;
    j:=1;
    while nr>0 and nc>0 do
        nzr:=true;
        nzb:=true;
        while nzr or nzb do
            nzr:=ForAny([1..i],i1->ForAny([j+1..nc],j1->rest[i1][j1]<>0));
            nzb:=ForAny([i+1..nr],i1->ForAny([1..j],j1->rest[i1][j1]<>0));
            if nzr then
                j:=j+1;
            fi;
            if nzb then
                i:=i+1;
            fi;
        od;
        Add(bls,List([1..i],i1->rest[i1]{[1..j]}));
        rest:=List([i+1..nr],i1->rest[i1]{[j+1..nc]});
        nr:=nr-i;
        nc:=nc-j;
        i:=1; j:=1;
    od;

    nbls:=Length(bls);

    # check if we have filled all columns and rows
    if nc>0 and nbls>0 then # add zeroes at the end of the last block
        bls[nbls]:=List(bls[nbls], l->Concatenation(l,List([1..nc],_->0)));
    fi;

    if nr>0 and nbls>0 then # add zero rows at the end of the last block
        bls[nbls]:=Concatenation(bls[nbls], List([1..nr],_->List([1..Length(bls[nbls])],_->0)));
    fi;

    return bls;

end;
```

**Comment by cdwensley** [comment]
Thanks - that does give one decomposition.  No time at present to study what the code actually does. 
Of course there is a third decomposition:  [ [[0,2],[0,0],[0,0]], [[3,0]] ]. 
(Puzzled by the "_"s in "_->".)

**Comment by hongyi-zhao** [comment]
@cdwensley 
> (Puzzled by the ""s in "->".)

What do you mean by saying this?

**Comment by hongyi-zhao** [comment]
@pedritomelenas 
> https://github.com/gap-packages/utils/issues/64#issuecomment-1590886181
> By the way, if I remember well, @hongyi-zhao told me that there would be no zero rows, and this is why I did not take them into account.

My description depends on my needs at the time. In short, the matrix I handled at that time was [the Gram matrix](https://en.wikipedia.org/wiki/Gram_matrix) of the basis of the translation lattice of a space group, which should meet the above statement. But in general, my above statement of course should not hold.

**Comment by hongyi-zhao** [comment]
@pedritomelenas @cdwensley 
> Thanks - that does give one decomposition. No time at present to study what the code actually does. Of course there is a third decomposition: [ [[0,2],[0,0],[0,0]], [[3,0]] ]. (Puzzled by the "_"s in "_->".)

I tried the latest implementation above, and only got one solution:

```gap
gap> M:=[[0,2,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,3,0]];
[ [ 0, 2, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 3, 0 ] ]
gap> DirectSumDecompositionMatrix(M);
[ [ [ 0, 2 ] ], [ [ 0 ] ], [ [ 0 ] ], [ [ 3, 0 ] ] ]
```

**Comment by hongyi-zhao** [comment]
I also don't know about this particular usage, but based on the simple test below, it's clear that its purpose is to generate a list of zeros with the corresponding length:

```gap
gap> List([1..3], _->0);
[ 0, 0, 0 ]
```

**Comment by hongyi-zhao** [comment]
@cdwensley 
> Very strange: it appears in my browser as “{underline}->”, and when I send “_->” to you the underline disappears? Must be a local effect.

See my explanation https://github.com/gap-packages/utils/issues/64#issuecomment-1591053468

**Comment by hongyi-zhao** [comment]
@cdwensley 

> I have yet to hear back from Max, and I may contact some of the other developers instead. It occurs to me that the development version of GAP contains a significant rewrite of matrix functions, so that this is probably not the time to be adding something to Utils. In the meantime I find that the proposed function fails on the following input: mat4 := [[0,2,0,0],[0,0,0,0],[0,0,0,0],[0,0,3,0]]; when I would hope for the answer: [ [[0,2],[0,0]], [[0,0],[3,0]] ].

Is there any news or progress regarding this matter?

**Comment by cdwensley** [comment]
No progress.  Why would you want this function to be generally available, anyway?  If so, why not wait for 4.13?

**Comment by hongyi-zhao** [comment]
> Why would you want this function to be generally available, anyway?

Because `DirectSumMat` already exists in GAP, its inverse operation should also exist in order to form a complete symmetric implementation.

> If so, why not wait for 4.13?

What do you mean by saying this?

**Comment by cdwensley** [comment]
Thank you @ThomasBreuer for this advice.  However, the function DiagonalMatrix is not available in gap-4.12.2 and the proposal  is to include DirectSumDecompositionMatrix in a new release of Utils now.  So I propose to release the current elementary version very soon, and a more comprehensive version once gap-13.1 (or whatever) is out.  That's unless you would advise otherwise.

**Comment by hongyi-zhao** [comment]
In fact, there are two implementations related to `DiagonalMatrix` in GAP:

```gap
gap> DiagonalMatrix( [ 1, 2 ], [ [ 1 ] ] );                           
[ [ 1, 0 ], [ 0, 2 ] ]
gap> DiagonalMat([1,2,3]);
[ [ 1, 0, 0 ], [ 0, 2, 0 ], [ 0, 0, 3 ] ]
```

**Comment by cdwensley** [comment]
Apologies for slow progress on this issue.  I've spent more time than I would wish on this, and have now released Utils PR #65.  The function has become recursive and now returns a list of decompositions.  There is a new chapter 6 in the manual.  There are further tests in utils/tst/matrix.tst, but I would urge you to try your own tests and find examples which fail.  I am aware that the function is inefficient when dealing with arrays with lots of zeroes, in that the various solutions are constructed multiple times, but optimising the code is not a priority for me.  All comments very welcome.

**Comment by hongyi-zhao** [comment]
Thanks, but there is a typo in [the commit name](https://github.com/gap-packages/utils/pull/65/commits/f95752b83e2b906783866610a216d1c57472ee3b):

![image](https://github.com/gap-packages/utils/assets/11155854/e50c0e10-94b4-471e-b6ea-535b4ec652f0)

added DirectSumCompositionMatrices

should be 

added DirectSumDecompositionMatrices

**Comment by cdwensley** [comment]
True, but cannot be changed, I believe.

**Comment by hongyi-zhao** [comment]
![image](https://github.com/gap-packages/utils/assets/11155854/d816a67c-231c-48a7-b297-7b99bb064773)

**Comment by cdwensley** [comment]
Thanks - done.

**Comment by cdwensley** [comment]
Decided it was time to close this issue. Utils v.0.84 released with the new Matrices chapter and revised test for DirectSumDecompositionMatrices.  There is still room for improvement in the code.
