### ISSUE TITLE
Extra "/" in PackageInfo.g

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/utils#7]
I have seen the following report from the check for package updates:
```
*** Package Utils - different PackageInfo.g URL:
 Our   : https://gap-packages.github.io/utils/PackageInfo.g
 Stored: https://gap-packages.github.io/utils//PackageInfo.g
```
It looks like a number of entries of Utils' PackageInfo.g are formed in a way that they contain an extra "/".

**Comment by cdwensley** [comment]
Dear Alexander 

Not at all sure what this means. 
I'll check with Max that it is not a ReleaseTools issue. 

Best wishes, Chris

**Comment by alex-konovalov** [comment]
@cdwensley @fingolfin should not be a ReleaseTools issue, unless PackageInfo.g is generated from there. If you will look at 
```
PackageWWWHome   := "https://gap-packages.github.io/utils/", 
README_URL       := Concatenation( ~.PackageWWWHome, "/README" ), 
PackageInfoURL   := Concatenation( ~.PackageWWWHome, "/PackageInfo.g" ), 
ArchiveURL       := Concatenation( ~.SourceRepository.URL, 
                                   "/releases/download/v", ~.Version,
                                   "/", ~.Packagename, "-", ~.Version ),
```
then you will see that there is an initial slash in  "/PackageInfo.g" and a trailing one in PackageWWWHome, so that's why it occurs twice. Same in  some other components.

**Comment by cdwensley** [comment]
Ah sorry - understood.  Chris

**Comment by cdwensley** [comment]
Version 0.39 to be released shortly.
Incidentally, the validation script in http://www.gap-system.org/Packages/Authors/authors.html does not pick this up:
Checking README_URL.
Checking https://gap-packages.github.io/utils//README for availability and text type.
Successful download of https://gap-packages.github.io/utils//README

Checking PackageInfoURL.
Checking https://gap-packages.github.io/utils//PackageInfo.g for availability and GAP readable type.
Successful download of https://gap-packages.github.io/utils//PackageInfo.g

**Comment by cdwensley** [comment]
Version 0.39 now released.

**Comment by fingolfin** [comment]
Well, strictly speaking, it's valid to have two slashes in there, so no reason for the validator to complain... though I guess it might be nice if it did anyway.
