### ISSUE TITLE
Replace IMMUTABLE_COPY_OBJ with Immutable

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/utils#8]
While it's only in the docs, the function `IMMUTABLE_COPY_OBJ` is an internal function. The public name is `Immutable`.

I partly suggest this as I want to remove `IMMUTABLE_COPY_OBJ`.

**Comment by cdwensley** [comment]
You will recall that in early versions of Utils the idea was to modify the library files global.g and oper.g, but it was eventually decided that this was too risky a procedure.  The file doc/appendix.xml documented this initial approach (including IMMUTABLE_COPY_OBJ in the revised version of DeclareGlobalFunction), but is no longer included in the current manual.  Unfortunately, the file appendix.xml remains in the distributed version - I will remove it as soon as I can.

**Comment by ChrisJefferson** [comment]
I will admit, I didn't look too carefully, I was just grepping packages for `IMMUTABLE_COPY_OBJ` :)
